version: '2.3'
services:
  dev:
    container_name: fujiwara_env
    image: rec_env:cuda11.3.1-py3
    runtime: nvidia
    working_dir: /home/student/Programs
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /home/student/Programs:/home/student/Programs
        - /data/:/data
    environment:
        - DISPLAY=unix$DISPLAY
        - TERM=xterm-256color
        - GRANT_SUDO:"yes"
    ports:
        - "8888:8888"
    command:
        jupyter-lab --ip 0.0.0.0 --allow-root -b localhost
    ulimits:
        memlock: -1
        stack: 67108864
    shm_size: 64g
    #stdin_open: true
    tty: true
